import {Dimensions, Platform, StyleSheet} from 'react-native';

const screenWidth = Dimensions.get('window').width;

export const styles = StyleSheet.create({
  button: {
    alignItems: 'center',
    backgroundColor: '#b8b8b8',
    borderRadius: 20,
    elevation: 2,
    flex: 1,
    padding: 10,
    margin: 1,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
  },
  buttonContainer: {
    alignItems: 'center',
    backgroundColor: '#fff',
    flex: 1,
    justifyContent: 'center',
    flexDirection: 'row',
  },
  buttonText: {
    color: 'black',
    fontWeight: 'bold',
  },
  buttonTextHome: {
    color: 'black',
    fontSize: 25,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  centeredView: {
    flex: 1,
  },
  column: {
    borderColor: '#000000',
    borderWidth: 2,
    flex: 1,
  },
  container: {
    alignItems: 'center',
    backgroundColor: '#fff',
    flex: 1,
    justifyContent: 'center',
  },
  header: {
    backgroundColor: '#ff7700',
    borderWidth: 2,
    height: 50,
    width: screenWidth,
  },
  headerText: {
    color: '#000000',
    fontSize: 32,
    padding: 5,
    textAlign: 'center',
  },
  homeGameCodeInput: {
    backgroundColor: 'white',
    borderWidth: 1,
    flexDirection: 'row',
    height: 40,
    margin: 12,
    padding: 10,
  },
  homePage: {
    alignContent: 'center',
    backgroundColor: '#fff',
    flex: 1,
  },
  homeTextWarning: {
    color: 'red',
    fontSize: 10,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalView: {
    margin: 20,
    marginTop: Platform.OS === 'ios' ? 100 : 20,
    backgroundColor: '#ff7700',
    borderColor: '#000000',
    borderRadius: 20,
    borderWidth: 1,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
  },
  playerNameInput: {
    backgroundColor: 'white',
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    height: 40,
    margin: 12,
    padding: 10,
  },
  playerScoreInput: {
    backgroundColor: 'white',
    borderWidth: 1,
    color: 'black',
    flex: 1,
    flexDirection: 'row',
    fontSize: 20,
    height: 40,
    padding: 10,
    textAlign: 'right',
    width: 300,
  },
  playerScoreInputContainer: {
    flex: 1,
    flexDirection: 'row',
    padding: 20,
  },
  pointsAndButtonWrapper: {
    flexDirection: 'row',
  },
  row: {
    backgroundColor: '#F7F8FA',
    borderColor: '#000000',
    borderTopWidth: 0,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderBottomWidth: 2,
    height: 40,
    width: screenWidth,
  },
  rowNameText: {
    fontSize: 18,
    color: '#000000',
    padding: 5,
    paddingLeft: 20,
  },
  rowScoreText: {
    color: '#000000',
    fontSize: 18,
    padding: 5,
    paddingRight: 20,
    textAlign: 'right',
  },
  table: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#fff',
    borderColor: '#000000',
    borderRadius: 10,
    flex: 9,
    justifyContent: 'center',
    textAlignVertical: 'top',
    width: screenWidth,
  },
});
